language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script: 
 - pytest
 - nosetests
 - coverage run --source=. py.test && nosetests && coverage report
 - coveralls
after_success: 
 - coveralls
 - coverage report